"""add governance ledger

Append-only, hash-chained audit records. `entry_hash` is unique so a replayed
entry cannot be appended twice; `subject_id` is intentionally not a foreign
key, because an audit record must outlive the decision it describes.

Revision ID: 5ad63a0cd8cd
Revises: 44c32b71d8f2
Create Date: 2026-08-22 03:12:53.072510
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "5ad63a0cd8cd"
down_revision: str | None = "44c32b71d8f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ledger_entries",
        sa.Column("seq", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("entry_hash", sa.String(length=64), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("subject_id", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("seq"),
    )
    op.create_index(
        op.f("ix_ledger_entries_entry_hash"), "ledger_entries", ["entry_hash"], unique=True
    )
    op.create_index(op.f("ix_ledger_entries_kind"), "ledger_entries", ["kind"], unique=False)
    op.create_index("ix_ledger_entries_kind_seq", "ledger_entries", ["kind", "seq"], unique=False)
    op.create_index(
        op.f("ix_ledger_entries_prev_hash"), "ledger_entries", ["prev_hash"], unique=False
    )
    op.create_index(
        op.f("ix_ledger_entries_recorded_at"), "ledger_entries", ["recorded_at"], unique=False
    )
    op.create_index(
        op.f("ix_ledger_entries_subject_id"), "ledger_entries", ["subject_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ledger_entries_subject_id"), table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_recorded_at"), table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_prev_hash"), table_name="ledger_entries")
    op.drop_index("ix_ledger_entries_kind_seq", table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_kind"), table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_entry_hash"), table_name="ledger_entries")
    op.drop_table("ledger_entries")
    # ### end Alembic commands ###
