"""trust snapshots

Revision ID: 644db26045e9
Revises: d05d6a97dc88
Create Date: 2026-08-20 00:40:45.676518
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "644db26045e9"
down_revision: str | None = "d05d6a97dc88"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trust_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("base_score", sa.Float(), nullable=False),
        sa.Column("anomaly_penalty", sa.Float(), nullable=False),
        sa.Column("factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason", sa.String(length=40), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trust_snapshots_agent_id"), "trust_snapshots", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_trust_snapshots_captured_at"), "trust_snapshots", ["captured_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trust_snapshots_captured_at"), table_name="trust_snapshots")
    op.drop_index(op.f("ix_trust_snapshots_agent_id"), table_name="trust_snapshots")
    op.drop_table("trust_snapshots")
    # ### end Alembic commands ###
