"""initial governance schema

Revision ID: d05d6a97dc88
Revises:
Create Date: 2026-08-19 23:03:55.006047
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "d05d6a97dc88"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_items",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("message", sa.String(length=400), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "tone",
            sa.Enum("info", "success", "warning", "danger", name="activity_tone"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activity_items_at"), "activity_items", ["at"], unique=False)
    op.create_table(
        "agents",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("capability", sa.String(length=120), nullable=False),
        sa.Column("owner", sa.String(length=120), nullable=False),
        sa.Column(
            "lifecycle",
            sa.Enum(
                "onboarding",
                "healthy",
                "anomaly",
                "review",
                "recovery",
                "trusted",
                name="lifecycle_state",
            ),
            nullable=False,
        ),
        sa.Column("trust_score", sa.Integer(), nullable=False),
        sa.Column("trust_delta", sa.Float(), nullable=False),
        sa.Column("decisions_today", sa.Integer(), nullable=False),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("authority_level", sa.Integer(), nullable=False),
        sa.Column("last_audit_at", sa.Date(), nullable=False),
        sa.Column("last_decision", sa.String(length=300), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "policies",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("scope", sa.String(length=160), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("low", "medium", "high", "critical", name="severity"),
            nullable=False,
        ),
        sa.Column("evaluations_24h", sa.Integer(), nullable=False),
        sa.Column("violations_24h", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_policies_enabled"), "policies", ["enabled"], unique=False)
    op.create_table(
        "decisions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=300), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum("approved", "escalated", "blocked", name="decision_outcome"),
            nullable=False,
        ),
        sa.Column("trust_score", sa.Integer(), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("investigation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_decisions_agent_id"), "decisions", ["agent_id"], unique=False)
    op.create_index(op.f("ix_decisions_decided_at"), "decisions", ["decided_at"], unique=False)
    op.create_index(op.f("ix_decisions_outcome"), "decisions", ["outcome"], unique=False)
    op.create_table(
        "trust_factors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_id", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trust_factors_agent_id"), "trust_factors", ["agent_id"], unique=False)
    op.create_table(
        "policy_checks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("decision_id", sa.String(length=64), nullable=False),
        sa.Column("policy_id", sa.String(length=64), nullable=False),
        sa.Column("policy_name", sa.String(length=200), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("detail", sa.String(length=300), nullable=True),
        sa.ForeignKeyConstraint(["decision_id"], ["decisions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_policy_checks_decision_id"), "policy_checks", ["decision_id"], unique=False
    )
    op.create_index(
        op.f("ix_policy_checks_policy_id"), "policy_checks", ["policy_id"], unique=False
    )
    op.create_table(
        "simulation_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("decision_id", sa.String(length=64), nullable=False),
        sa.Column("scenario", sa.String(length=300), nullable=False),
        sa.Column("agent_name", sa.String(length=200), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("trust_score", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "recommendation",
            sa.Enum("approved", "escalated", "blocked", name="decision_outcome"),
            nullable=False,
        ),
        sa.Column("ran_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("request", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["decision_id"], ["decisions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_simulation_runs_decision_id"), "simulation_runs", ["decision_id"], unique=False
    )
    op.create_index(op.f("ix_simulation_runs_ran_at"), "simulation_runs", ["ran_at"], unique=False)
    op.create_table(
        "simulation_outcomes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("financial_impact_usd", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("compliant", sa.Boolean(), nullable=False),
        sa.Column("customer_experience", sa.String(length=20), nullable=True),
        sa.Column("compliance_risk", sa.String(length=20), nullable=True),
        sa.Column("recommended", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["simulation_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_simulation_outcomes_run_id"), "simulation_outcomes", ["run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_simulation_outcomes_run_id"), table_name="simulation_outcomes")
    op.drop_table("simulation_outcomes")
    op.drop_index(op.f("ix_simulation_runs_ran_at"), table_name="simulation_runs")
    op.drop_index(op.f("ix_simulation_runs_decision_id"), table_name="simulation_runs")
    op.drop_table("simulation_runs")
    op.drop_index(op.f("ix_policy_checks_policy_id"), table_name="policy_checks")
    op.drop_index(op.f("ix_policy_checks_decision_id"), table_name="policy_checks")
    op.drop_table("policy_checks")
    op.drop_index(op.f("ix_trust_factors_agent_id"), table_name="trust_factors")
    op.drop_table("trust_factors")
    op.drop_index(op.f("ix_decisions_outcome"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_decided_at"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_agent_id"), table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(op.f("ix_policies_enabled"), table_name="policies")
    op.drop_table("policies")
    op.drop_table("agents")
    op.drop_index(op.f("ix_activity_items_at"), table_name="activity_items")
    op.drop_table("activity_items")
    # ### end Alembic commands ###

    # Alembic drops tables but not the enum types they used, which makes a
    # downgrade/upgrade cycle fail with "type ... already exists".
    for enum_name in ("decision_outcome", "lifecycle_state", "severity", "activity_tone"):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
